version: '3.5'

services:
  mysql:
    image: mysql:5.7
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_USER: sakila
      MYSQL_PASSWORD: sakila
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
    - 3306:3306
    networks:
    - datalabframework
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d:ro

networks:
  datalabframework:
    external: true
